services:
  productsmicroservice.api:
    container_name: productsmicroservice.api
    build:
      context: ./ProductsMicroService.API
      dockerfile: Dockerfile
    image: usercontianerregistry.azurecr.io/productserviceapp:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ASPNETCORE_URLS=http://+:8080
    ports:
       - "8080:8080"
      # - "5259:7000"
    networks:
      - ocelot-shared-network

networks:
  ocelot-shared-network:
    external: true